---
# Image that contains tox and tons of Python versions:
image: fkrull/multi-python

stages:
  - test
# - deploy

linting:
  stage: test
  script:
    - tox -e py36-lint,py37-lint,py38-lint

pytest:
  stage: test
  script:
    - tox -e py36,py37,py38

pages:
  stage: deploy
  image: python:3.7-alpine
  script:
    - pip install sphinx==3.3.1 sphinx-rtd-theme sphinx_autodoc_typehints sphinx_markdown_builder
    - sphinx-build -b html docs/source .public
    - mv .public public

  artifacts:
    paths:
      - public
