---
# Image that contains tox and tons of Python versions:
image: fkrull/multi-python

stages:
  - test
  - deploy

linting:
  stage: test
  script:
    - tox -e py36-lint,py37-lint,py38-lint

pytest:
  stage: test
  script:
    - tox -e py36,py37,py38

pages:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y python3-venv python3-pip
    - python3 -m venv env
    - env/bin/pip install --upgrade pip
    - env/bin/pip install -U sphinx sphinx-rtd-theme sphinx_autodoc_typehints sphinx_markdown_builder
    - sphinx-build -b html docs/source .public
    - mv .public public
  
  artifacts:
    paths:
      - public
