---
# Image that contains tox and tons of Python versions:
image: fkrull/multi-python

stages:
  - test

linting:
  stage: test
  script:
    - tox -e py36-lint,py37-lint,py38-lint

pytest:
  stage: test
  script:
    - tox -e py36,py37,py38

pages:
  stage: test
  script:
  - pip install -r requirements.txt
  - mv build/html public
  artifacts:
    paths:
    - public
  only:
  - main
