---
# Image that contains tox and tons of Python versions:
image: fkrull/multi-python

stages:
  - test
  - deploy

linting:
  stage: test
  script:
    - tox -e py36-lint,py37-lint,py38-lint

pytest:
  stage: test
  script:
    - tox -e py36,py37,py38

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r build/* .public
    - mv .public public
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public

  artifacts:
    paths:
      - public
