---
# Image that contains tox and tons of Python versions:
image: fkrull/multi-python

stages:
#  - test
  - deploy

linting:
  stage: test
  script:
    - tox -e py36-lint,py37-lint,py38-lint

pytest:
  stage: test
  script:
    - tox -e py36,py37,py38

pages:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y virtualenv python3-pip git
    - virtualenv env
    - env/bin/pip install --upgrade pip
    - env/bin/pip install wheel sphinx==3.3.1 sphinx-rtd-theme sphinx_autodoc_typehints sphinx_markdown_builder tensorflow torch torchvision
    - env/bin/pip install .
    - cd docs && make html
    - mkdir .public
    - cp -r docs/build/html/* .public
    - mv .public public
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public

  artifacts:
    paths:
      - public
