---
image: themattrix/tox

before_script:
  - apt update && apt-get install liblzma-dev

stages:
  - test

linting:
  stage: test
  script:
    - tox -e py36-lint,py37-lint,py38-lint

pytest:
  stage: test
  script:
    - tox -e py36,py37,py38
