# .pre-commit-config.yaml
# ========================
#
# pre-commit clean
# pre-commit install
# pre-commit install-hooks
#
# precommit hooks installation
#
# - pre-commit autoupdate
#
# - pre-commit run black
#
# continuous integration
# ======================
#
# - pre-commit run --all-files
#

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: LICENSES/headers
    - id: check-added-large-files

  # - repo: https://github.com/timothycrosley/isort
  #   rev: 5.10.1
  #   hooks:
  #   - id: isort

  # - repo: https://github.com/ambv/black
  #   rev: 21.11b1
  #   hooks:
  #   - id: black
  #     language_version: python3.8

  # - repo: https://github.com/psf/black
  #   rev: 21.11b1
  #   hooks:
  #   - id: black

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 4.0.1
  #   hooks:
  #   - id: flake8
  #     additional_dependencies:
  #       - flake8-bugbear==21.3.2
  #       # 1.6.0 has a bug
  #       # https://gitlab.com/pycqa/flake8-docstrings/-/issues/51
  #       - flake8-docstrings==1.5.0
  #       - flake8-logging-format==0.6.0
  #       - flake8-print==4.0.0
  #       - pep8-naming==0.11.1

  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v2.20.0
  #   hooks:
  #     - id: commitizen
  #       stages: [commit-msg]

  # # - repo: https://github.com/Lucas-C/pre-commit-hooks
  # #   rev: v1.1.10
  # #   hooks:
  # #     - id: insert-license
  # #       name: insert MIT license
  # #       exclude: ^(docs/source)
  # #       files: \.py$
  # #       args:
  # #         - --license-filepath
  # #         - LICENSES/headers/MIT-Clause.txt


  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: v2.6.0
  #   hooks:
  #     - id: reorder-python-imports

  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v2.20.0
  #   hooks:
  #     - id: commitizen
  #       stages: [commit-msg]
